name: flutterbasestructure
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #language
  flutter_localizations:
    sdk: flutter
  sprintf: ^4.0.2
  
  #network
  retrofit: ^1.3.4+1

  #base
  flutter_bloc: ^7.0.0
  shared_preferences: ^2.0.5
  
  #utils
  logger: ^1.0.0
  pedantic: ^1.8.0 # Analysis and unawaited
  date_format: ^2.0.2
  connectivity: ^3.0.3

  #ui
  cached_network_image: ^3.0.0
  fluttertoast: ^8.0.3
  flutter_statusbarcolor_ns: ^0.3.0-nullsafety
  flutter_spinkit: ^5.0.0
  flutter_easyloading: ^3.0.0

dependency_overrides:
  dio: ^4.0.0
  http_parser: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  retrofit_generator: ^1.4.1+3

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/languages/
   - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
