name: flutterbasestructure
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  #language
  flutter_localizations:
    sdk: flutter
  sprintf: ^6.0.0
  
  #network
  retrofit: ^2.0.1 #ns
  graphql_flutter: ^5.0.0 #ns

  #base
  flutter_bloc: ^7.2.0 #ns
  shared_preferences: ^2.0.7 #ns
  get_it: ^7.2.0 #ns
  intl: ^0.17.0 #ns
  flutter_svg_provider: ^0.1.10 #ns
  flutter_svg: ^0.22.0 #ns
  
  #utils
  logger: ^1.0.0 #ns
  pedantic: ^1.11.1 #ns
  date_format: ^2.0.2 #ns
  connectivity_plus: ^1.1.0

  #ui
  cached_network_image: ^3.1.0 #ns
  fluttertoast: ^8.0.8 #ns
  flutter_statusbarcolor_ns: ^0.3.0-nullsafety #ns
  flutter_spinkit: ^5.1.0 #ns
  flutter_easyloading: ^3.0.3 #ns

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4 #ns
  retrofit_generator: ^2.0.0+1 #ns

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/languages/
   - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
